# Generated by Django 4.0.4 on 2022-05-11 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoContatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.PositiveIntegerField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.PositiveIntegerField(max_length=8, verbose_name='CEP')),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('dataCadastro', models.DateField(default=datetime.date(2022, 5, 11))),
                ('grupoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='contatos.grupocontatos')),
            ],
        ),
    ]
