# Generated by Django 4.0.4 on 2022-05-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocontatos',
            name='titulo',
            field=models.CharField(default=1, max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
