# Generated by Django 4.0.4 on 2022-05-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_grupocontatos_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='grupoCliente',
            new_name='grupoContato',
        ),
    ]
