# Generated by Django 4.0.4 on 2022-05-11 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_rename_grupocliente_contato_grupocontato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='dataCadastro',
            field=models.DateField(default=datetime.date(2022, 5, 11), verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='grupoContato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='contatos.grupocontatos', verbose_name='Grupo do Contato'),
        ),
    ]
